server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456


  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 0


## Mybatis \u914D\u7F6E
mybatis:
  type-aliases-package: com.chen.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true



